apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pg.pvc_name }}
  namespace: {{ .Values.meshdb_app_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi