apiVersion: v1
kind: Secret
metadata:
  name: meshdb-secrets
  namespace: {{ .Values.meshdb_app_namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.pg.password | b64enc | quote }}
  aws-access-key-id: {{ .Values.aws.access_key_id | b64enc | quote }}
  aws-secret-access-key: {{ .Values.aws.secret_access_key | b64enc | quote }}
  django-secret-key: {{ .Values.meshweb.django_secret_key | b64enc | quote }}
  nn-assign-psk: {{ .Values.meshweb.nn_assign_psk | b64enc | quote }}
  query-psk: {{ .Values.meshweb.query_psk | b64enc | quote }}
  uisp-pass: {{ .Values.uisp.psk | b64enc | quote }}
  pano-github-token: {{ .Values.meshweb.pano_github_token | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: {{ .Values.longhorn.key | quote }}
  CRYPTO_KEY_PROVIDER: "secret"
