version: '3'
services:
  postgres:
    network_mode: "host"
    image: docker.io/postgres:latest
    environment:
      POSTGRES_DB: ${MESHDB_DB_NAME}
      POSTGRES_USER: ${MESHDB_DB_USER} 
      POSTGRES_PASSWORD: ${MESHDB_DB_PASSWORD}
    start_period: 3s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
