version: '3'
services:
  postgres:
    networks:
      - api
    ports:
      - 5432:5432
    image: docker.io/postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 10s 
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - postgres-storage:/var/lib/postgresql/data/

  meshdb:
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
    #entrypoint: "gunicorn wsgi:app --graceful-timeout 5 --bind=0.0.0.0:8080"

volumes:
  postgres-storage:

networks:
  api:
