on:
  push:
    branches: [ "main", "james/checkov" ]
  workflow_dispatch:
jobs:
  checkov-job:
    permissions:
      actions: read
      checks: none
      contents: read
      deployments: none
      discussions: none
      id-token: none
      issues: none
      packages: none
      pages: none
      repository-projects: none
      security-events: write
      statuses: none
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@0549dc60bddd4c55cb85c6c3a07072e3cf2ca48e
        with:
          skip_check: CKV_DOCKER_2,CKV_DOCKER_3
          quiet: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
          download_external_modules: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
