name: Integration

on: [pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:latest
#        # `POSTGRES_HOST` is `postgres`
#        env:
#          POSTGRES_DB: nycmesh-dev
#          POSTGRES_USER: nycmesh
#          POSTGRES_PASSWORD: helloThisIsATest
#          POSTGRES_PORT: 5432
#        ports:
#          # maps tcp port 5432 on service container to the host
#          - 5432:5432
#        # set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres
            meshdb
        env:
          MESHDB_DB_NAME: nymesh-dev
          MESHDB_DB_USER: nycmesh
          MESHDB_DB_HOST: postgres
          MESHDB_DB_PASSWORD: helloThisIsATest
      - name: "Run Integration Test Script"
        run: |
          env | grep MESHDB > .env
          ./tests/run_integration.sh -d
        env:
          MESHDB_DB_NAME: nymesh-dev
          MESHDB_DB_USER: nycmesh
          MESHDB_DB_HOST: postgres
          MESHDB_DB_PASSWORD: helloThisIsATest
