
name: Integration

on: [pull_request]

jobs:
  integration-test-ephemeral:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: "Install Dependencies"
        run: |
          pip install --upgrade pip
          pip install '.[dev]'
      - name: "Start meshdb API"
        run: gunicorn 'meshdb:create_app()' --graceful-timeout 5 --bind=0.0.0.0:8080 & sleep 3
        env:
          DB_NAME: nycmesh-dev
          DB_USER: nycmesh
          DB_HOST: postgres
          DB_PASSWORD: abcd1234
          SECRET_KEY: ${{ secrets.MESHDB_SECRET_KEY }}
          SECRET_PASSWORD_SALT: ${{ secrets.MESHDB_SECRET_PASSWORD_SALT }}
      - name: "Run Integration Test Script"
        run: |
          PYTHONPATH=. pytest . 
        env:
          DB_NAME: nycmesh-dev
          DB_USER: nycmesh
          DB_HOST: postgres
          DB_PASSWORD: abcd1234
          SECRET_KEY: ${{ secrets.MESHDB_SECRET_KEY }}
          SECRET_PASSWORD_SALT: ${{ secrets.MESHDB_SECRET_PASSWORD_SALT }}
