name: Integration

on: [pull_request]

jobs:
  integration-test-ephemeral:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: helloThisIsATest
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: "Install Dependencies"
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
      - name: "Start meshdb API"
        run: gunicorn meshdb:app --graceful-timeout 5 --bind=0.0.0.0:8080 & sleep 3
      - name: "Run Integration Test Script"
        run: |
          PYTHONPATH=. pytest . 
        env:
          MESHDB_DB_NAME: nymesh-dev
          MESHDB_DB_USER: nycmesh
          MESHDB_DB_HOST: localhost
          MESHDB_DB_PASSWORD: helloThisIsATest
