name: Make sure Debug mode is OFF!

on: [pull_request]

jobs:
  is-debug-off:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Your PR is not running in debug mode"
        run: cd src && python3 -c "import meshdb.settings; assert meshdb.settings.DEBUG == False"
