name: Run Django Tests

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: "Upgrade pip"
        run: "pip install --upgrade pip"
      - name: "Install package"
        run: pip install ".[dev]"
      - name: Run Django Tests
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_PORT: 5432
        run: python3 src/manage.py test meshapi
